### ISSUE TITLE
clone下来 测试了下 ，报错

### ISSUE THREAD

**Issue by Super-Man** [esrrhs/majiang_algorithm#1]
![image](https://user-images.githubusercontent.com/7392930/39223412-907676a4-4874-11e8-971c-fa2c0c8d947e.png)

gen() 这个是放开注释了的
load txt以后 ，testOut、testPeng、testGang、都会报同样的错误。是我使用姿势不对？

**Comment by esrrhs** [comment]
如果你只是测试的话，gen不能放开，放开后会重新生成数据文件。如果你生成一半停止了，数据文件就不全了，你再load自然会报错。你回滚修改，更新最新，用idea打开，应该不会报错

**Comment by Super-Man** [comment]
有QQ么？有问题的话 方便请教你

**Comment by Super-Man** [comment]
方便留个QQ 么？ 有问题的话可以随时请教你

**Comment by esrrhs** [comment]
372552720
