### ISSUE TITLE
你好请问下这个概率是怎么算的呢？看了一天没看懂

### ISSUE THREAD

**Issue by IsQiao** [esrrhs/majiang_algorithm#10]
1万2万5万5万：无将 0.006099681251811069（这手牌如果不做将，能胡的概率是0.006）
1万2万5万5万：有将 0.03433398152649489（这手牌如果做将，能胡的概率是0.03，因为有现成5万的将，只需要3万就能胡）

**Comment by esrrhs** [comment]
就是给他几张牌，看看能形成3n+2或者3n的概率

**Comment by IsQiao** [comment]
哦哦 这样啊 我算算 稍等 感谢

**Comment by IsQiao** [comment]
是不是 假设有5张牌 然后5张牌（1万到5万）的所有组合里有1万2万5万5万且组成了
n1*AAA+n2*ABC+1*DD(有将、无将)的个数占全部数量的百分比
这样就可以了吧
