### ISSUE TITLE
想请问下.这套代码用在长麻上不知道知否能行.

### ISSUE THREAD

**Issue by manBoooooooooooooom** [esrrhs/majiang_algorithm#11]
我本地单元测试的时候,发现必须要有鬼牌.但是长麻是没有鬼牌的.想要稍加改造 但部分逻辑不是很明白.

**Comment by esrrhs** [comment]
算法肯定是兼容无鬼牌的，看看测试代码调用的接口，换一个即可

**Comment by manBoooooooooooooom** [comment]
您好，请问下长麻这一块是二，五，八才能做将。我如何修改gen()里面的代码呢 让生成的文件数据是二，五，八做将？

**Comment by manBoooooooooooooom** [comment]
又或者说。只有指定的二五八做将的算法，该是修改哪一块呢？读您的代码 但确实没有找到与将相关的代码块

**Comment by esrrhs** [comment]
那就找到生成表的代码，修改有将无将的那块判断代码即可
