### ISSUE TITLE
请教概率计算方法及相关代码

### ISSUE THREAD

**Issue by AOZMH** [esrrhs/majiang_algorithm#12]
您好！

非常感谢提出的算法，对我很有启发性。不过我在查看了readme和 #10 后仍然没有很懂概率是如何计算的。
请问：
* 对于每一组牌，所谓”看看能形成3n+2或者3n的概率“里面这个n应该如何取呢？
* 应该如何决定是计算3n+2还是3n的概率呢？
* 您所说的计算概率的每一"组"牌，就是同样花色的所有牌嘛（比如当前13张牌中所有的筒，或者所有的条）？
* 能否分享一下计算概率的代码是在哪里实现的呢？

感谢您的帮助！

**Comment by esrrhs** [comment]
你说的是胡牌算法还是AI算法？

**Comment by AOZMH** [comment]
是ai算法

**Comment by esrrhs** [comment]
对于每一组牌，所谓”看看能形成3n+2或者3n的概率“里面这个n应该如何取呢？
n只是一个公式，n属于正整数
    应该如何决定是计算3n+2还是3n的概率呢？
都计算，分别是有将和无将的概率
    您所说的计算概率的每一"组"牌，就是同样花色的所有牌嘛（比如当前13张牌中所有的筒，或者所有的条）？
万筒条是一样的，计算一次即可。东西南北，中发白需要再计算
    能否分享一下计算概率的代码是在哪里实现的呢？
https://github.com/esrrhs/majiang_algorithm/blob/master/src/main/java/com/github/esrrhs/majiang_algorithm/AIUtil.java#L329

**Comment by AOZMH** [comment]
抱歉，还是想进一步问一下这个概率的计算过程。
就以您提到的“一万两万五万五万”为例，考虑有将的胡牌概率；您提到拿到三万就能胡，所以可以计算抽到三万的概率。但是这一组牌还有其他胡牌的方式，例如抽到两个一万两个两万，这样可以组成“一万*3，两万*3，五万*2”也能胡，又例如之后可以打出去一万和两万，只剩下一对五万，也能胡。请问这样的话是否需要枚举（搜索）各种后续牌面情况来计算总概率呢？如果是，应该如何搜索呢？以及，对应这块的代码是否是[check_ai](https://github.com/esrrhs/majiang_algorithm/blob/master/src/main/java/com/github/esrrhs/majiang_algorithm/AICommon.java#L171)与[gen_cards](https://github.com/esrrhs/majiang_algorithm/blob/master/src/main/java/com/github/esrrhs/majiang_algorithm/AICommon.java#L313)呢，这两个函数的作用分别是什么呢？
谢谢！

**Comment by esrrhs** [comment]
群里沟通吧，这样沟通效率太低了
