### ISSUE TITLE
能不能在表里 生成  鬼牌替换的牌吗？ 

### ISSUE THREAD

**Issue by thisperfect** [esrrhs/majiang_algorithm#2]
鬼牌替换的牌，主要用于某些地方特殊的算番。

还有单表太大,按鬼个数拆表会不会好一点。  

另外  无鬼牌时候 似乎没法兼容

麻烦 大神了

**Comment by esrrhs** [comment]
代码很简单的，可以自己fork修改

**Comment by esrrhs** [comment]
无鬼牌时候 为啥不兼容？ 鬼牌传0就好了

**Comment by thisperfect** [comment]
guiNum += cards.get(gui - 1);
				cards.set(gui - 1, 0);
有这种代码。  gui  不好取值哇。  取0 那 数组访问-1 报错。   其他的...
