### ISSUE TITLE
牌型分数计算

### ISSUE THREAD

**Issue by ChenG0207** [esrrhs/majiang_algorithm#5]
你好 能请教一下 牌型的具体计算吗？ 1万 2万 5万 5万 这个牌型有将 算出的概率为 36/9/136 = 0.02941176470588235294117647058824 与你给的概率 不一致 望指教一下

**Comment by esrrhs** [comment]
36/9/136是啥概率？这个要计算的概率是再摸几张牌，这个能胡的概率是多少
