### ISSUE TITLE
牌型分类

### ISSUE THREAD

**Issue by qx** [esrrhs/majiang_algorithm#6]
胡牌后我想知道胡牌的摆法,这个怎么入手改呢

**Comment by esrrhs** [comment]
相当于需要知道鬼牌变成的牌吗？

**Comment by qx** [comment]
对,可以简单点,先算无鬼的情况

**Comment by qx** [comment]
这个需求还是比较实际的,是在生成表的时候直接写入数据呢?还是在查出来后再算一次,如果再算是不是有点不合适,如果生成表,应该在哪改,gen_card?

**Comment by esrrhs** [comment]
对，改gencard生成的地方，不过需要注意数据量问题

**Comment by qx** [comment]
怎么改能否给点思路,gencard出来的牌是不是一定满足3n+2组合?

**Comment by esrrhs** [comment]
代码很简单吧，看看改改即可

**Comment by qx** [comment]
带癞子的情况呢?算法这东西简单复杂因人而异吧

**Comment by esrrhs** [comment]
生成的算法其实就是穷举鬼牌的变化，看看是不是胡了，你就在胡的时候，把鬼牌当时穷举的牌记下来就好了。其实我推荐是先用查表算法判断胡不胡，如果胡了，再去穷举那几张鬼牌，看看他最大胡的牌型是什么，已经知道胡了，再去判断胡牌的牌型，很简单也很快
