### ISSUE TITLE
内存占用太大了

### ISSUE THREAD

**Issue by ghost** [esrrhs/majiang_algorithm#9]

**Comment by Sparks1525** [comment]
内存占用太大了

**Comment by esrrhs** [comment]
还好啊，太大是多大？生成表的时候内存大无所谓，关键看使用查表的时候大不大

**Comment by ghost** [comment]
加载完表之后400m，最大800m，有没有办法能优化下，谢谢大佬

**Comment by esrrhs** [comment]
400m那是因为读表的关系 gc一下就没了

**Comment by ghost** [comment]
HuCommon类中的load()方法不需要关闭FileInputStream流吗？

**Comment by esrrhs** [comment]
有可能这的问题 😂 我回头改下发个maven版本

**Comment by esrrhs** [comment]
> 
> 
> HuCommon类中的load()方法不需要关闭FileInputStream流吗？

更新了 1.0.15

**Comment by ghost** [comment]
谢谢，辛苦了大佬
